### ISSUE TITLE
[Issue] Group Excluding broken

### ISSUE THREAD

**Issue by Uronic** [Silenci0/UMC#10] opened 2019-03-08 08:07 UTC
Every time I try to edit the group exclude cvar for rtv endvote etc. it just makes the voting menu not appear when voting starts.

**Comment by Silenci0** [comment] 2019-03-09 08:04
Hello,

Would you mind posting your umc endvote configuration file and your umc_mapcycle.txt file please? This will help me determine where the bug might be that is causing the vote menu to not appear.

**Comment by Uronic** [comment] 2019-03-09 13:32
`// This file was auto-generated by SourceMod (v1.3.8)
// ConVars for plugin "umc-endvote.smx"


/////////////////////////////////////////////////////////////////////////////////////
// Full Documentation for the End of Map Vote module is located at:                //
//      http://code.google.com/p/sourcemod-ultimate-mapchooser/wiki/ModuleEndVote  //
/////////////////////////////////////////////////////////////////////////////////////


// Specifies which admin flags are necessary for a player to participate in a vote. If empty, all players can participate.
// -
// Default: ""
sm_umc_endvote_adminflags ""

// Allows a map to appear in the vote more than once. This should be enabled if you want the same map in different categories to be distinct.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_umc_endvote_allowduplicates "1"

// When to change the map after a successful vote:
//  0 - Instant,
//  1 - Round End,
//  2 - Map End
// -
// Default: "2"
// Minumum: "0.000000"
// Maximum: "2.000000"
sm_umc_endvote_changetime "2"

// File to use for Ultimate Mapchooser's map rotation.
// -
// Default: "umc_mapcycle.txt"
sm_umc_endvote_cyclefile "umc_mapcycle.txt"

// Specifies how long a vote should be available for.
// -
// Default: "20"
// Minimum: "10.000000"
sm_umc_endvote_duration "20"

// Specifies if Ultimate Mapchooser should run an end of map vote.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_umc_endvote_enabled "1"

// Sound file (relative to sound folder) to play at the completion of an end-of-map vote.
// -
// Default: ""
sm_umc_endvote_endsound ""

// Specifies how many more frags each extension adds to the frag limit.
// -
// Default: "10"
// Minimum: "1.000000"
sm_umc_endvote_extend_fragstep "10"

// Specifies how many more rounds each extension adds to the round limit.
// -
// Default: "5"
// Minimum: "1.000000"
sm_umc_endvote_extend_roundstep "5"

// Specifies how many more minutes each extension adds to the time limit.
// -
// Default: "15"
// Minimum: "1.000000"
sm_umc_endvote_extend_timestep "15"

// Number of extensions allowed each map.
//  0 disables the Extend Map option.
// -
// Default: "0"
// Minimum: "0.000000"
sm_umc_endvote_extends "1"

// Specifies what action to take if the vote doesn't reach the set theshold.
//  0 - Do Nothing,
//  1 - Perform Runoff Vote
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_umc_endvote_failaction "1"

// Specifies how many past map groups to exclude from the end of map vote.
// -
// Default: "0"
// Minimum: "0.000000"
sm_umc_endvote_groupexclude "0"

// Specifies how many past maps to exclude from the end of map vote. 1 = Current Map Only
// -
// Default: "4"
// Minimum: "0.000000"
sm_umc_endvote_mapexclude "4"

// Specifies whether vote menu items are displayed in a random order.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_umc_endvote_menuscrambled "1"

// Specifies whether the number of nominated maps appearing in the vote for a map group should be limited by the group's "maps_invote" setting.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_umc_endvote_nominate_strict "0"

// Determines whether End of Map Votes should be delayed until the end of the round in which they were triggered.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_umc_endvote_onroundend "0"

// Delays the vote by the number of seconds specified for votes that are triggered on round end. (Due to mp_maxrounds or mp_winlimit)
// -
// Default: "0"
// Minimum: "0.000000"
sm_umc_endvote_roundend_delaystart "0"

// Specifies what action to take if the runoff vote reaches the maximum amount of runoffs and the set threshold has not been reached.
//  0 - Do Nothing,
//  1 - Change Map to Winner
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_umc_endvote_runoff_failaction "1"

// Specifies the maximum number of maps to appear in a runoff vote.
//  1 or 0 sets no maximum.
// -
// Default: "0"
// Minimum: "0.000000"
sm_umc_endvote_runoff_max "0"

// If specified, this sound file (relative to sound folder) will be played at the beginning of a runoff vote. If not specified, it will use the normal vote start sound.
// -
// Default: ""
sm_umc_endvote_runoff_sound ""

// Specifies a maximum number of runoff votes to run for any given vote.
//  0 = unlimited.
// -
// Default: "0"
// Minimum: "0.000000"
sm_umc_endvote_runoffs "0"

// Specifies when to start the vote based on frags remaining.
// -
// Default: "10"
// Minimum: "1.000000"
sm_umc_endvote_startfrags "10"

// Specifies when to start the vote based on rounds remaining. Use 0 on TF2 to start vote during bonus round time
// -
// Default: "2"
// Minimum: "0.000000"
sm_umc_endvote_startrounds "2"

// Sound file (relative to sound folder) to play at the start of an end-of-map vote.
// -
// Default: ""
sm_umc_endvote_startsound ""

// Specifies when to start the vote based on time remaining in minutes.
// -
// Default: "6"
// Minimum: "1.000000"
sm_umc_endvote_starttime "6"

// If a winning vote has less than this percentage of total votes, a runoff vote will be held.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_umc_endvote_threshold "0"

// Controls end of map vote type:
//  0 - Maps,
//  1 - Groups,
//  2 - Tiered Vote (vote for a group, then vote for a map from the group).
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "2.000000"
sm_umc_endvote_type "2"
`

`// Mapcycle definition for Ultimate Mapchooser v3.1 by Steell

///////////////////////////////////////////////////////////////////////////////
//***************************************************************************//
//**                           ULTIMATE MAPCHOOSER                         **//
//***************************************************************************//
// The format of this file is as specified in the following example:         //
//                                                                           //
// "umc_mapcycle"                                                            //
// {                                                                         //
//      "GROUPNAME-1" //Name of the group, used by group votes.              //
//      {                                                                    //
//          //Text to display for maps from this group in the vote. If left  //
//          //blank or omitted, the map's name will be used as the default.  //
//          //The following string will be replaced when parsed:             //
//          //  {MAP}           =   The map's name                           //
//          //  {NOMINATED}     =   If nominated, a string determined by the //
//          //                      "sm_umc_nomination_display" cvar in      //
//          //                      "ultimate-mapchooser.cfg"                //
//          //  {MIN_PLAYERS}                                                //
//          //  {MAX_PLATERS}   =   The "min_players" and "max_players"      //
//          //                      settings for the map.                    //
//          //  {MIN_TIME}                                                   //
//          //  {MAX_TIME}      =   The "min_time" and "max_time" settings   //
//          //                      for the map.                             //
//          // (Default value: "{MAP}")                                      //
//          "display-template"      "any value"                              //
//            //Defined in "umc-core.smx"                                    //
//                                                                           //
//          //Number of maps to include from this group in a vote.           //
//          // (Default value: 1)                                            //
//          "maps_invote"           "int >= 0"                               //
//            //Defined in "umc-core.smx"                                    //
//                                                                           //
//          //The weight of this group for random picking. Higher numbers    //
//          //mean the group is more likely to be picked. 0 means the group  //
//          //can never be picked randomly.                                  //
//          // (Default value: 1)                                            //
//          "group_weight"          "float > 0"                              //
//            //Defined in "umc-weight.smx"                                  //
//                                                                           //
//          //If a map from this group is picked randomly or via vote, the   //
//          //next time a map is chosen randomly, it will be from the group  //
//          //specified in this setting. If "" then a random group is picked.//
//          // (Default value: "")                                           //
//          "next_mapgroup"         "Group Name"                             //
//            //Defined in "umc-randomcycle.smx"                             //
//                                                                           //
//          //Used as defaults if "min_players" or "max_players" is          //
//          //not defined for a map in this group.                           //
//          // (Default value: 0)                                            //
//          "default_min_players"   "int >= 0"                               //
//          // (Default value: Player limit of the server)                   //
//          "default_max_players"   "int >= 0"                               //
//            //Defined in "umc-playerlimits.smx"                            //
//                                                                           //
//          //Used as defaults if "min_time" or "max_time" is not defined    //
//          //for a map in this group.                                       //
//          // (Default value: "0000")                                       //
//          "default_min_time"  "HHMM, where HH is the hour and MM is the    //
//                               minute"                                     //
//          // (Default value: "2359")                                       //
//          "default_max_time"	    "HHMM"                                   //
//            //Defined in "umc-timelimits.smx"                              //
//                                                                           //
//          //Used as default if "allow_every" is not defined for a map in   //
//          //this group.                                                    //
//          // (Default value: 0)                                            //
//          "default_allow_every"   "int >= 0"                               //
//            //Defined in "umc_postexclude.smx"                             //
//                                                                           //
//          //The command specified here is performed at the start of all    //
//          //maps in this group.                                            //
//          // (Default value: "")                                           //
//          "command"   "any valid console command"                          //
//            //Defined in "umc-mapcommands.smx"                             //
//                                                                           //
//          //Players need to have at least one admin flag specified in this //
//          //string in order to nominate this map.                          //
//          // (Default value: "")                                           //
//          "nominate_flags"    "sequence of admin flags"                    //
//            //Defined in "umc-nominate.smx"                                //
//                                                                           //
//          //Admins need to have at least one admin flag specified in this  //
//          //string in order to see this map in the admin menu.             //
//          // (Default value: "")                                           //
//          "adminmenu_flags"   "sequence of admin flags"                    //
//            //Defined in "umc-adminmenu.smx"                               //
//                                                                           //
//          "MAP-1" //Name of a map, must be a valid map.                    //
//          {                                                                //
//              //Text to display for this map in the vote. If left blank    //
//              //or omitted, the map's name will be used instead.           //
//              // (Default value: "{MAP}")                                  //
//              "display"       "any value"                                  //
//                //Defined in "umc-core.smx"                                //
//                                                                           //
//              //The weight of this map with reference to other maps        //
//              //in this category. This number affect how likely the        //
//              //map will appear in a vote, as well as how likely this      //
//              //map will be chosen randomly (assuming this group has       //
//              //already been chosen.)                                      //
//              // (Default value: 1)                                        //
//              "weight"        "float > 0"                                  //
//                //Defined in "umc-weight.smx"                              //
//                                                                           //
//              //Overrides the option of the same name in the group level.  //
//              // (Default value: "")                                       //
//              "next_mapgroup"     "Group Name"                             //
//                //Defined in "umc-randcycle.smx"                           //
//                                                                           //
//              //Defines the number of players required to be on the        //
//              //server in order for this map to be used.                   //
//              // (Default values: see "default_min_players" and            //
//              //  "default_max_players")                                   //
//              "min_players"   "int >= 0"                                   //
//              "max_players"   "int >= 0"                                   //
//                //Defined in "umc-playerlimits.smx"                        //
//                                                                           //
//              //Defines the minimum and maximum times that UMC will pick   //
//              //this map to be played.                                     //
//              "min_time"      "HHMM"                                       //
//              "max_time"      "HHMM"                                       //
//                //Defined in "umc-timelimits.smx"                          //
//                                                                           //
//              //Defines an amount of time in minutes that a map is to be   //
//              //excluded from selection after it has been played.          //
//              "allow_every"   "int >= 0"                                   //
//                //Defined in "umc-postexclude.smx"                         //
//                                                                           //
//              //This command is performed at the start of this map. Note:  //
//              //The command specified here is performed AFTER the one      //
//              //specified for the group, and does not override it.         //
//              // (Default value: "")                                       //
//              "command"       "any valid console command"                  //
//                //Defined in "umc-mapcommands.smx"                         //
//                                                                           //
//              //Players need to have at least one admin flag specified in  //
//              //this string in order to nominate this map. This overrides  //
//              //the option  specified by this group for this map.          //
//              // (Default value: "")                                       //
//              "nominate_flags"    "sequence of admin flags"                //
//                //Defined in "umc-nominate.smx"                            //
//                                                                           //
//              //Admins need to have at least one admin flag specified in   //
//              //this string in order to see this map in the admin menu.    //
//              //This overrides the option specified by this group for this //
//              //map.                                                       //
//              // (Default value: "")                                       //
//              "adminmenu_flags"   "sequence of admin flags"                //
//                //Defined in "umc-adminmenu.smx"                           //
//                                                                           //
//              //When this map is nominated, it is associated with the group//
//              //specified by this setting, overriding the group that it's  //
//              //physically located in within this definition file. If blank//
//              //it uses the group it's currently located in.               //
//              // (Default value: "")                                       //
//              "nominate_group"    "Group Name"                             //
//                //Defined in "umc-core.smx"                                //
//          }                                                                //
//                                                                           //
//          "MAP-2"                                                          //
//          {                                                                //
//              ...                                                          //
//          }                                                                //
//                                                                           //
//          ...                                                              //
//                                                                           //
//          "MAP-N"                                                          //
//          {                                                                //
//              ...                                                          //
//          }                                                                //
//      }                                                                    //
//                                                                           //
//      "GROUPNAME-2"                                                        //
//      {                                                                    //
//          ...                                                              //
//      }                                                                    //
//                                                                           //
//      ...                                                                  //
//                                                                           //
//      "GROUPNAME-N"                                                        //
//      {                                                                    //
//          ...                                                              //
//      }                                                                    //
// }                                                                         //
//***************************************************************************//
//*                      ^YOU MAY DELETE THIS SECTION^                      *//
///////////////////////////////////////////////////////////////////////////////

"umc_mapcycle"
{
    "Hide and Seek"
    {
        "maps_invote"   "5"

        "minecraft_by_howl" { "display"		"Minecraft by Howl (HNS)" }
		"skyskrapers" { "display"		"Skyscrapers (HNS)" }
		"hns_wintervillage1" { "display"		"Winter Village (HNS)" }
		"Total_Shutdown"{ "display"		"Total Shutdown (HNS)" }
		"seek_hotel"{ "display"		"Hotel (HNS)" }
    }
	
    "Death Run"
    {
        "maps_invote"   "5"

        "deathrun_12000BC_v1" { "display"		"12000 BC (DR)" }
		"deathrun_absolute_beta" { "display"		"Absolute Beta (DR)" }
		"deathrun_bananaland_sn2" { "display"		"Bananaland SN2 (DR)" }
		"deathrun_castlerun_v4" { "display"		"Castle Run (DR)" }
		"deathrun_holyshit_stable_4" { "display"		"Holyshit (DR)" }
		"deathrun_iceworld_v2fix_csgo" { "display"		"Iceworld (DR)" }
		"deathrun_lego_world_final" { "display"		"Lego World (DR)" }
		"deathrun_second_installation" { "display"		"Second Installation (DR)" }
		"deathrun_simpsons_ff" { "display"		"Simpsons FF (DR)" }
		"deathrun_warehouse" { "display"		"Warehouse (DR)" }
		"dr_kanker_clean" { "display"		"Kanker Clean (DR)" }
		"dr_oldschool" { "display"		"Old School (DR)" }
    }
	
    "Mini Games"
    {
        "maps_invote"   "5"

		"mg_16_battles_csgo" { "display"		"16 Battles (MG)" }
		"mg_awpknivez_jungle_alpha" { "display"		"Awpknivez Jungle (MG)" }
		"mg_bear_attack_hard_CSStoGO" { "display"		"Bear Attack Hard (MG)" }
		"mg_bhop_battle_ag" { "display"		"Bhop Battle AG (MG)" }
		"mg_clouds_multigames_v2" { "display"		"Clouds Multigames (MG)" }
		"mg_grands_multigames_v1_1" { "display"		"Grands Multigames (MG)" }
		"mg_koga73_multigames_h" { "display"		"Koga73 Multigames (MG)" }
		"mg_longroad_2" { "display"		"Long Road (MG)" }
		"mg_lt_glacier_csgo_v2" { "display"		"lt Glacier (MG)" }
		"mg_nature_multigames_v2" { "display"		"Nature Multigames (MG)" }
		"mg_piratewars_island" { "display"		"Piratewars Island (MG)" }
		"mg_potatogames_04" { "display"		"Potato Games (MG)" }
		"mg_randomizer_reborn_v2" { "display"		"Randomizer Reborn (MG)" }
		"mg_raphi_multigame" { "display"		"Raphi Multigames (MG)" }
		"mg_ski_mountain_resort_CSStoGO" { "display"		"Ski Mountain Resourt (MG)" }
		"mg_smash_cannonsz_CSStoGO2" { "display"		"Smash Cannonsz (MG)" }
		"mg_streetbasketball" { "display"		"Street Basketball (MG)" }
		"mg_summer_tower_v1" { "display"		"Summer Tower (MG)" }
		"mg_swag_multigames_v7" { "display"		"Swag Multigames (MG)" }
		"mg_weapon_case_arenas_v1_2" { "display"		"Weapon Case Arenas (MG)" }
		"mg_yolo_multigames_v2_1" { "display"		"Yolo Multigames (MG)" }
		"mg_Zetzui_Multigames_v5" { "display"		"Zetzui Multigames (MG)" }
    }
	
    "TTT"
    {
        "maps_invote"   "5"

		"ttt_community_bowling_csgo_v3" { "display"		"Community Bowling (TTT)" }
		"ttt_factory_temper_beta1_fixed" { "display"		"Factory Temper (TTT)" }
		"ttt_island17_pezversion" { "display"		"Island 17 (TTT)" }
		"ttt_kirbycity_b3_1" { "display"		"Kirby City (TTT)" }
		"ttt_mcvillage_b3-c" { "display"		"MC Village (TTT)" }
		"ttt_richburg" { "display"		"Richburg (TTT)" }
		"ttt_roy_the_ship_csgoport_v3_1" { "display"		"Roy the Ship (TTT)" }
		"ttt_sky_islands_csgo_v2" { "display"		"Sky Islands (TTT)" }
		"ttt_teenroom_csgo_2" { "display"		"Teenroom (TTT)" }
		"ttt_tumbleweed_v1_3" { "display"		"Tumble Weed (TTT)" }
    }

    "Retakes"
    {
        "maps_invote"   "5"
		"command" "exec sourcemod/umc/de.cfg"

		"de_cache" { "display"		"Cache (Retakes)" }
		"de_cbble" { "display"		"Cobble (Retakes)" }
		"de_dust2" { "display"		"Dust 2 (Retakes)" }
		"de_inferno" { "display"		"Infernew (Retakes)" }
		"de_mirage" { "display"		"Mirage (Retakes)" }
		"de_nuke" { "display"		"Nuke (Retakes)" }
		"de_overpass" { "display"		"Overpass (Retakes)" }
		"de_train" { "display"		"Train (Retakes)" }
    }

    "Gun Game"
    {
        "maps_invote"   "5"

		"GG_crash_arabian" { "display"		"Crash Arabian (GG)" }
		"gg_simpsons_street_go" { "display"		"Simpsons Street (GG)" }
		"gg_lego2011_csgo_v2" { "display"		"Lego2011 (GG)" }
		"gg_blender_csgo" { "display"		"Blender (GG)" }
		"gg_townsquare" { "display"		"Town Square (GG)" }
		"gg_neon_snow" { "display"		"Neon Snow (GG)" }
		"gg_cargoship_csgo" { "display"		"Cargo Ship (GG)" }
    }
	
	"SurfPVP"
	{
		"maps_invote" "5"
		
		"surf_10x_reloaded_for_csgo_v2" { "display"		"10x Reloaded (SurfPVP)" }
		"surf_aero_violence" { "display"		"Aero Violence (SurfPVP)" }
		"surf_altitude" { "display"		"Altitude (SurfPVP)" }
		"surf_dust2_2008_csgo_rfix" { "display"		"Dust2 2008 (SurfPVP)" }
		"surf_iceday" { "display"		"Iceday (SurfPVP)" }
		"surf_japan_ptad_swg" { "display"		"Japan (SurfPVP)" }
		"surf_mirage_2018" { "display"		"Mirage (SurfPVP)" }
		"surf_ski_2_spectrum_v40_pak" { "display"		"Ski 2 Spectrum (SurfPVP)" }
		"surf_vortex" { "display"		"Vortex (SurfPVP)" }
		"surf_xiv_csgo_rfix" { "display"		"Xiv (SurfPVP)" }
		"surf_year3000_dm_csgo" { "display"		"Year3000 (SurfPVP)" }
	}
	
	"Prop Hunt"
	{
		"maps_invote" "5"
		"command" "exec sourcemod/umc/cs.cfg"
		
		"cs_agency" { "display"		"Agency (Prophunt)" }
		"cs_assault" { "display"		"Assault (Prophunt)" }
		"cs_italy" { "display"		"Italy (Prophunt)" }
		"cs_militia" { "display"		"Militia (Prophunt)" }
		"cs_office" { "display"		"Office (Prophunt)" }
		"ar_monastery" { "display"		"Monastery (Prophunt)" }
		"de_cache" { "display"		"Cache (Prophunt)" }
		"de_cbble" { "display"		"Cobble (Prophunt)" }
		"de_dust2" { "display"		"Dust 2 (Prophunt)" }
		"de_inferno" { "display"		"Infernew (Prophunt)" }
		"de_mirage" { "display"		"Mirage (Prophunt)" }
		"de_nuke" { "display"		"Nuke (Prophunt)" }
		"de_overpass" { "display"		"Overpass (Prophunt)" }
		"de_train" { "display"		"Train (Prophunt)" }
		"de_vertigo" { "display"		"Vertigo (Prophunt)" }
	}
	
	"Base Builder"
	{
		"maps_invote" "5"
		
		"bb_boomix" { "display"		"Boomix (Base Builder)" }
		"bb_castle" { "display"		"Castle (Base Builder)" }
		"bb_corners7" { "display"		"Corners7 (Base Builder)" }
		"bb_cs16_modern" { "display"		"CS1.6 Modern (Base Builder)" }
		"bb_developer2" { "display"		"Developer2 (Base Builder)" }
		"bb_dust2_maincra_fix" { "display"		"Dust2 Maincra (Base Builder)" }
		"bb_frozen" { "display"		"Frozen (Base Builder)" }
		"bb_karper_v3" { "display"		"Karper (Base Builder)" }
		"bb_kindlus_v4" { "display"		"Kindlus (Base Builder)" }
		"bb_kyku" { "display"		"Kyku (Base Builder)" }
		"bb_mevid_r2" { "display"		"Mevid (Base Builder)" }
		"bb_pentagon_b1" { "display"		"Pentagon (Base Builder)" }
		"bb_sandstorm" { "display"		"Sandstorm (Base Builder)" }
		"bb_street_beta" { "display"		"Street (Base Builder)" }
		"bb_westwood" { "display"		"Westwood (Base Builder)" }
		"bb_zipoz_minecraft" { "display"		"Zipoz Minecraft (Base Builder)" }
		"bb_zipoz_v2_sloneczny" { "display"		"Zipoz Sloneczny (Base Builder)" }
		"bb_zipoz_umbrella_corp" { "display"		"Zipoz Umbrella Corp (Base Builder)" }
		"bb_amisu_lego" { "display"		"Amisu Lego (Base Builder)" }
		"bb_amisu_aztec" { "display"		"Amisu Aztec (Base Builder)" }
		"bb_amisu_minecraft" { "display"		"Amisu Minecraft (Base Builder)" }
		"bb_amisu_mega" { "display"		"Amisu Mega (Base Builder)" }
		"bb_amisu_lego_mini" { "display"		"Amisu Lego Mini (Base Builder)" }
		"bb_assault" { "display"		"Assault (Base Builder)" }
		"bb_King" { "display"		"King (Base Builder)" }
		"bb_dust" { "display"		"Dust (Base Builder)" }
		"bb_india_" { "display"		"India (Base Builder)" }
		"bb_minecraft_2016" { "display"		"Minecraft 2016 (Base Builder)" }
		"bb_snow_s" { "display"		"Snow (Base Builder)" }
		"bb_big" { "display"		"Big (Base Builder)" }
		"bb_train" { "display"		"Train (Base Builder)" }
		"bb_classic" { "display"		"Classic (Base Builder)" }
		"bb_amisu" { "display"		"Amisu (Base Builder)" }
	}
	
    "FFA"
    {
        "maps_invote"   "5"
		"command" "exec sourcemod/umc/ffa.cfg"

		"de_cache" { "display"		"Cache (FFA)" }
		"de_cbble" { "display"		"Cobble (FFA)" }
		"de_dust2" { "display"		"Dust 2 (FFA)" }
		"de_inferno" { "display"		"Infernew (FFA)" }
		"de_mirage" { "display"		"Mirage (FFA)" }
		"de_nuke" { "display"		"Nuke (FFA)" }
		"de_overpass" { "display"		"Overpass (FFA)" }
		"de_train" { "display"		"Train (FFA)" }
    }
	
	"Zombie Plague"
	{
        "maps_invote"   "5"

		"zp_aztec_infinity_d_16toGO" { "display"		"Aztec Infinity (ZP)" }
		"zp_cpl_egyptian_16toGO" { "display"		"CPL Egyptian (ZP)" }
		"zp_fun_world_4_16toGO" { "display"		"Fun World 4 (ZP)" }
		"zp_gbox6_16toGO" { "display"		"GBox 6 (ZP)" }
		"zp_gbox7_16toGO" { "display"		"GBox 7 (ZP)" }
		"zp_restart_16toGO" { "display"		"Restart (ZP)" }
		"zp_trakinax_turbo_16toGO" { "display"		"Trakinax Turbo (ZP)" }
    }
	
	"A.W.P"
	{
        "maps_invote"   "5"

		"awp_1337" { "display"		"1337 (AWP)" }
		"awp_india_csgo" { "display"		"India (AWP)" }
		"awp_invaders" { "display"		"Invaders (AWP)" }
		"awp_lego_2" { "display"		"Lego 2 (AWP)" }
		"awp_lego_asia" { "display"		"Lego Asia (AWP)" }
		"awp_minecraft_crash_go" { "display"		"Minecraft Crash (AWP)" }
		"awp_pro" { "display"		"Pro (AWP)" }
		"awp_soviet_v1" { "display"		"Soviet (AWP)" }
		"awp_tridust" { "display"		"Tridust (AWP)" }
		"awp_vietnam" { "display"		"Vietnam (AWP)" }
		"awp_zigzag" { "display"		"Zigzag (AWP)" }
    }
}
`

**Comment by Silenci0** [comment] 2019-07-21 03:40
Hello,

I realize this is a rather late response, but after finally managing to have the time to sit down and work on UMC as well as check on this issue, I found that I could not reproduce it using the same endvote config that you posted (thanks again for posting that). I also don't see an issue with your umc-mapcycle.txt file, so it looks correctly formatted. With all that said, my testing was done in TF2 and not in CS:GO, so perhaps that might make a difference here.

Despite the game being different, functionally, my test should mean the exclude feature does work in UMC endvote, but it could also mean that this is a CS:GO specific issue, so I will be doing a few tests with UMC on CS:GO. In the meantime, I am labeling this issue as a CS:GO bug (for now). I will respond when I have more info regarding this issue.

**Comment by Silenci0** [comment] 2019-08-14 09:56
I have tested this in CS:GO with the latest UMC version (3.7.0) and Group Exclusions work there as well. I believe your configurations are fine and, if there was a bug in the last version, it should be fixed now. If it still persists, it might be due to another issue unrelated to UMC or it is another configuration file interfering. I will be closing this issue since it should be resolved now. Please let me know if further bugs/issues occur.

**Closed by Silenci0** 2019-08-14 09:56 UTC
Labels: CS:GO, potential bug
