### ISSUE TITLE
Maps not in group show in vote.

### ISSUE THREAD

**Issue by StrikerMan780** [Silenci0/UMC#1] opened 2018-07-03 00:15 UTC
When using tiered votes, maps that aren't in a particular group end up showing in the group when they're not supposed to. (Payload maps show in the CTF group, as an example)

I've noticed this in end map votes and rtv's.

**Comment by Silenci0** [comment] 2018-07-03 09:58
Are the maps you see in the vote list nominated maps? One of the newer features ensures that map nominations by players would show up first and at the top of any voting list, particularly for end map votes and rtvs. This was added since a few communities, particularly from ZPS, wanted to make sure player nominated maps would take priority and show up first in the list during a map vote. 

Assuming the maps you see in the votes are seeing are nominated maps, I could attempt to limit it to just rtv only as an option. Disabling map nominations may fix this (though you would only be allowed to vote on map choices presented solely by the plugin) or setting the cvar sm_umc_mapnom_display to 0 in the ultimate-mapchooser.cfg file will display all map nominations at the bottom of the list (which was the default for the plugin a long time ago). As far as these votes showing up in the tiered votes list, that sounds like a bug, so I'll look into it. However, if you can verify if the maps that show up are in fact nominated maps, I would be most grateful.

**Comment by StrikerMan780** [comment] 2018-07-03 19:07
Turns out this bug happens when umc-playerlimits.smx is absent.

**Comment by Silenci0** [comment] 2018-07-04 05:10
Its odd that playerlimits would resolve that, which makes me wonder if maybe older versions had a similar problem and no one ever noticed before. I will look into what might cause tiered voting and the playerlimits module have that might be causing that particular issue. Thank you for the clarification!

**Comment by Silenci0** [comment] 2018-07-05 12:46
After looking over the comments on the original plugin, it seems that this issue you had with tiered voting also existed with that as well and adding the playerlimits module also resolved the issue, which means the bug has been present for a long time.

So the quick solution to this issue is to add that module to fix tiered voting. Long term, I will look to see how to resolve this so that playerlimits is no longer necessary for tiered votes.

**Comment by Silenci0** [comment] 2018-11-30 05:48
After looking into this, this is not a bug so much as it is intentional design. The umc-playerlimits.smx module is necessary for some tiered voting and groupings depending on the options used and will be required for proper operation. The general fix to this will be to include the umc-playerlimits.smx module. Closing issue.

**Closed by Silenci0** 2018-11-30 05:48 UTC
